GET http://127.0.0.1:9200/iris_uat_steeleye_co_accountuser/_search


###

GET http://127.0.0.1:9200/iris_uat_steeleye_co_accountuser/_mapping

###

GET http://127.0.0.1:9200/iris_uat_steeleye_co_accountuser/_search

{
    "query": {
        "wildcard": {
            "name": "*mee*"
        }
    }
}