GET http://127.0.0.1:9200/iris_uat_steeleye_co_accountuser/_search

###

GET http://127.0.0.1:9200/iris_uat_steeleye_co_accountuser/_mapping

###

GET http://127.0.0.1:9200/iris_uat_steeleye_co_accountuser/_search

{
    "query": {
        "wildcard": {
            "name": "*mee*"
        }
    }
}

###

GET http://127.0.0.1:5000/api/v2.1/comms?take=10&f=timestamps.timestampStart.hour inrange [0,17]&sort=timestamps.timestampStart%3Adesc
Authorization: {{token}}