version: '3.0'
services:
  elasticsearch:
    container_name: es-container
    image: 'docker.elastic.co/elasticsearch/elasticsearch:8.13.2'
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    networks:
      - elastic
    ports:
      - '9200:9200'
    volumes:
      - /home/sumeet/docker/data/elasticsearch:/usr/share/elasticsearch/data:rw
    restart: unless-stopped
  kibana:
    container_name: kb-container
    depends_on:
      - elasticsearch
    image: 'docker.elastic.co/kibana/kibana:8.13.2'
    networks:
      - elastic
    ports:
      - '5601:5601'
    volumes:
      - /home/sumeet/.config/docker/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
    restart: unless-stopped
networks:
  elastic:
    driver: bridge
